version: '3.8'
services:
  mysql:
    privileged: true
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'userdb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    image: mysql:8.0
