version: "3"
services:
  db:
    image: postgres:14.1
    deploy:
      mode: global    
    environment:
      - POSTGRES_USER=am
      - POSTGRES_PASSWORD=am
      - POSTGRES_DB=am
    ports:
      - "5432:5432"
    volumes:
      - "C:/Users/richja/projects/Akros-Marketplace/datamodel/data:/var/lib/postgresql/data"

